USE [master]
GO

/****** Object:  Database [BODEGA]    Script Date: 08/02/2022 21:48:22 ******/
CREATE DATABASE [BODEGA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BODEGA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BODEGA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BODEGA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BODEGA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BODEGA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BODEGA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BODEGA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BODEGA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BODEGA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BODEGA] SET ARITHABORT OFF 
GO

ALTER DATABASE [BODEGA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BODEGA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BODEGA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BODEGA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BODEGA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BODEGA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BODEGA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BODEGA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BODEGA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BODEGA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BODEGA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BODEGA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BODEGA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BODEGA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BODEGA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BODEGA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BODEGA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BODEGA] SET RECOVERY FULL 
GO

ALTER DATABASE [BODEGA] SET  MULTI_USER 
GO

ALTER DATABASE [BODEGA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BODEGA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BODEGA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BODEGA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BODEGA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BODEGA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BODEGA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BODEGA] SET  READ_WRITE 
GO


USE [BODEGA]
GO

/****** Object:  Table [dbo].[Stock]    Script Date: 08/02/2022 21:23:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Stock](
	[ID_PRODUCTO] int IDENTITY(1,1) NOT NULL,
	[NOMBRE_PRODUCTO] [varchar](50) NULL,
	[ESTADO] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED 
(
	[ID_PRODUCTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Stock] ADD  CONSTRAINT [DF_Table_1_ESTADO]  DEFAULT ('Funcionando') FOR [ESTADO]
GO


